  
name: nf-fastqc branch protection
# This workflow is triggered on PRs to master branch on the repository
# It fails when someone tries to make a PR against the nf-fastqc `master` branch instead of `dev`
on:
  pull_request_target:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # PRs to the nf-fastqc repo master branch are only ok if coming from the nf-fastqc repo `dev` or any `patch` branches
      - name: Check PRs
        if: github.repository == 'bioinfo-tsukuba/nf-fastqc'
        run: |
          { [[ ${{github.event.pull_request.head.repo.full_name }} == bioinfo-tsukuba/nf-fastqc ]] && [[ $GITHUB_HEAD_REF = "dev" ]]; } || [[ $GITHUB_HEAD_REF == "patch" ]]
